---
- name: install xfce packages
  tags: configuration
  dnf:
    name: 
      - "{{ xfce4_packages }}"
      - "{{ xfce4_group_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

- name: enable gdm service
  tags: configuration
  systemd:
    name: gdm
    enabled: true
    state: started

- name: Set default target to graphical.target using shell
  shell: systemctl set-default graphical.target 
  args:
    executable: /bin/bash
  failed_when: false

- name: Copy xfce configuration files to force xfce as default desktop environment
  tags: configuration
  copy:
    src: standard
    dest: /etc/accountsservice/user-templates/standard
    owner: root
    group: root
    mode: "0644"
 
- name: Hide user options to choose other desktop environments than xfce
  tags: configuration
  lineinfile:
    path: "{{ item }}"
    regexp: '^#?WaylandEnable='
    line: 'WaylandEnable=false'
  with_items:
    - /etc/gdm/custom.conf

- name: Create a DIRs
  tags: configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755" 
  loop: 
    - /etc/xdg/autostart
    - /etc/skel/Desktop
    - /etc/skel/.config/autostart
    - /usr/share/xsessions.disabled

- name: Create a Launcher direcrories
  ansible.builtin.file:
    dest: /etc/skel/.config/xfce4/panel/launcher-{{ item }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_sequence: start=13 end=15 format=%02d 
  
- name: Look if the folder contains the files
  find:
    path: /usr/share/xsessions
    file_type: file
    patterns: "*.desktop"
    excludes: "xfce.desktop"
  register: desktopfile  

- name: Move unused sessions (excluding xfce.desktop)
  command:
    cmd: mv "{{ item.path }}" /usr/share/xsessions.disabled/
  loop: "{{ desktopfile.files }}"
  when: desktopfile.files

- name: Copy Shortcut to /etc/skel/Desktop
  tags: configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - "{{ shortcuts_for_desktop }}"

- name: Copy launcher & CONKY files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0664"
  with_items: 
    - "{{ launcher_and_conky_files }}"

- name: copy template for control panel menu
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop: 
    - "{{ templates_for_control_panel_menu }}"
  notify: restart gdm
    



